### PR TITLE
Get wqp sites and pull data

### PR DESCRIPTION
**Pull request by limnoliver**
This workflow is mostly the same that is used in the lake-temp-model-prep WQP pull that @aappling-usgs engineered. Briefly, the workflow:

1. Finds all sites with water temperature data in WQP
2. Take an inventory of the data available at each of the sites
3. Partitions data into multiple pulls in order to not max out the web service call
4. Pushes data to shared (USGS) google drive folder

The differences between this workflow and the lakes temp pull are:

1. I defined the sites within this workflow, as we do not have an upstream sites definition or crosswalk. I did this by using `whatWQPsites` using [these arguments](https://github.com/USGS-R/2wp-temp-observations/pull/1/files#diff-f8a5644af3b990873245e701e0dc117e). 

2. Because of the above site definitions without a crosswalk to NHDIDs, pull partitioning is not based on NHDID groupings. So, temperature data for a single stream segment or lake (with multiple sites) may be stored in separate files. I don't think this will be a huge deal since we do have a crosswalk table between all sites and which pull (file) they are located in. 

One potential solution to this is to use the site metadata to do some coarse site alignment. Most sites have state/county metadata, most have HUC 8 info, and all have lat/long. 

------------------------
This PR does a "test" pull of [subset of 100 sites](https://github.com/USGS-R/2wp-temp-observations/pull/1/files#diff-8e6bd481064c336d5996c68ac6d32f9eR36). I started with 50 and moved to 100, and it seems to be working properly when you add sites. E.g., the old sites are not repulled from NWIS.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
> One potential solution to this is to use the site metadata to do some coarse site alignment. Most sites have state/county metadata, most have HUC 8 info, and all have lat/long.

How does site batching work right now? If we did this grouping and then a couple new sites popped up, would that mean we'd need to pull a whole batch or two of sites just to add those new sites? And would that be any different (in efficiency) from what is coded right now?

**Comment by aappling-usgs** [comment]
I'm about to dive into the code and so may learn for myself, but can you say off-hand what the strategy is for updating to add new times as opposed to new sites? I ask because I think for this project either (1) we shouldn't worry much about incremental additions in space or time because we should really just repull _everything_ periodically, or (2) if we do want to worry about incremental additions, we should probably worry about them in both space and time dimensions.

**Comment by limnoliver** [comment]
```How does site batching work right now? If we did this grouping and then a couple new sites popped up, would that mean we'd need to pull a whole batch or two of sites just to add those new sites? And would that be any different (in efficiency) from what is coded right now?```

There essentially is none, it just goes in order the sites are listed and lumps sites together until we reach the size threshold. The way I envisioned the batching would be that you would have to re-pull the whole batch because you're saying they should belong in separate files. So I think it would be _less_ efficient than what is pulled now. Currently, if you add new sites, the new sites belong to a new pull, and the old files are unaffected.

```I'm about to dive into the code and so may learn for myself, but can you say off-hand what the strategy is for updating to add new times as opposed to new sites? I ask because I think for this project either (1) we shouldn't worry much about incremental additions in space or time because we should really just repull everything periodically, or (2) if we do want to worry about incremental additions, we should probably worry about them in both space and time dimensions.```

There is no strategy for adding new time. So, if you did a new inventory of sites with temperature observations (because you wanted the latest data), it would only add new sites that came online in the interim, and would ignore sites we already have that have new (in time) data. I agree with you that I think for this project, we would wipe everything away and repull.

**Comment by limnoliver** [comment]
Agree - feels like we're converging on a somewhat standard approach.

**Pull request merged**
